config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'meals#index'

  resources :meals do 
    resources :ingredients, only: [:new, :create]
    resources :directions,  only: [:new, :create]
  end

  resources :entries

  

end

app/models/concerns/taggable.rb
module Taggable
  extend ActiveSupport::Concern

  MEALTYPE = %w(Breakfast Lunch Dinner Snack)

  included do
    validates :meal_type, inclusion: {in: MEALTYPE, message: " (Meal) must be selected"}
  end

  # class_methods do
  # end

end

app/models/direction.rb
class Direction < ActiveRecord::Base 

  belongs_to :meal
  
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  include Taggable
  
  belongs_to :meal
  belongs_to :user

  has_one :nutrition, as: :subject, dependent: :destroy
  accepts_nested_attributes_for :nutrition, reject_if: :all_blank

  nilify_blanks

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  
  belongs_to :meal

end

app/models/meal.rb
class Meal < ActiveRecord::Base

  belongs_to :user
  has_many   :ingredients, dependent: :destroy
  has_many   :directions,  dependent: :destroy
  has_many   :entries,     dependent: :destroy
  has_one    :nutrition,   as: :subject, dependent: :destroy
  has_many   :tags,        through: :meal_tags
  has_many   :meal_tags,   dependent: :destroy
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank
  accepts_nested_attributes_for :directions,  reject_if: :all_blank
  accepts_nested_attributes_for :nutrition,   reject_if: :all_blank
  accepts_nested_attributes_for :tags,        reject_if: :all_blank
  accepts_nested_attributes_for :meal_tags,   reject_if: :all_blank

  validates :name, :servings, presence: true
  
  mount_uploader :avatar, AvatarUploader
  
  def self.search(search)
    like_operator = Rails.env.production? ? "ILIKE" : "LIKE"
    where("name #{like_operator} ?", "%#{search}%")
  end


end

app/models/meal_tag.rb
class MealTag < ActiveRecord::Base
  belongs_to :meal
  belongs_to :tag
end

app/models/nutrition.rb
class Nutrition < ActiveRecord::Base
  belongs_to :subject, polymorphic: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :user
  has_many   :meals,     through: :meal_tags
  has_many   :meal_tags, dependent: :destroy
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :meals,   dependent: :destroy
  has_many :entries, dependent: :destroy
  has_many :tags,    dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!

end

app/controllers/entries_controller.rb
require "pp"

class EntriesController < ApplicationController

  before_filter :set_meal_type, only: [:index, :new, :create]

  def index
    @user = current_user
    if params[:date]
      @start = Date.parse(params[:date]).at_beginning_of_week
    else
      @start = Date.today.at_beginning_of_week
    end

    @week = @start..@start+5.days
    @entry = Entry.new
    @entry.build_nutrition
  end

  def new
    @entry = Entry.new

  end

  def create
    @entry = Entry.new(entry_params)
    
    if @entry.save
      flash[:success] = "#{@entry.meal_type} was successfully added."
      redirect_to(:back)
    else
      flash[:info] = "The meal was not successfully added."
      redirect_to(:back)
    end
  end

  def destroy
    @entry = Entry.find(params[:id])
    @entry.destroy
    flash[:info] = "#{@entry.meal_type} has been successfully deleted."
    redirect_to(:back)
  end

  private

    def entry_params
      params.require(:entry).permit(
        :day, 
        :meal_type,
        :note,
        :meal_id,
        :user_id, 
        :nutrition_attributes   => [:calories, :protein, :carbs, :fat]
      )
    end

    def set_meal_type
      @meal_type = Entry::MEALTYPE
    end
    
end

app/controllers/meals_controller.rb
require "pp"

class MealsController < ApplicationController
  before_filter :set_meal, only: [:show, :update, :edit, :destroy]

  def index  
    if params[:search]
      @meals = current_user.meals.search(params[:search]) 
    elsif params[:tag]
      @meals = current_user.tags.find_by(name: params[:tag]).meals
    else 
      @meals = current_user.meals
    end

      @meals = @meals.order("id DESC").paginate(:page => params[:page], :per_page => 5)
    end

  def show
    @ingredients = @meal.ingredients
    @directions  = @meal.directions
  end

  def new
    @meal = Meal.new
    
    3.times { @meal.directions.build }
    5.times { @meal.ingredients.build }

    @meal.build_nutrition
  end

  def create
    @meal = Meal.new(meal_params)
    

    if @meal.save
      create_tags
      flash[:success] = "#{@meal.name} has been successfully created."
      redirect_to @meal
    else
      flash.now[:danger] = "The meal could not be created."
      render action: "new"
    end
  end

  def edit
    @meal.build_nutrition unless @meal.nutrition.present?

    unless @meal.ingredients.present?
      3.times do 
        @meal.ingredients.build 
      end
    end

    unless @meal.directions.present?
      3.times do 
        @meal.directions.build 
      end
    end
  end

  def update
    if @meal.update_attributes(meal_params)
      create_tags
      redirect_to @meal
    else
      render action: "edit"
    end
  end

  def destroy
    @meal.destroy
    flash[:info] = "#{@meal.name} has been successfully deleted."
    redirect_to meals_path
  end


  private
  
    def meal_params
      params.require(:meal).permit(
        :name, 
        :description, 
        :tag, 
        :servings, 
        :avatar, 
        :user_id,
        :ingredients_attributes => [:name, :amount, :id], 
        :directions_attributes  => [:step, :id],
        :nutrition_attributes   => [:calories, :protein, :carbs, :fat],
        :tags_attributes        => [:name, :color, :user_id, :id]
      )
    end

    def set_meal
      @meal = Meal.find(params[:id])
      return render file: "public/401.html" if @meal.user_id != current_user.id
    end

    def create_tags
      @meal.meal_tags.destroy_all

      return if params[:tags].nil?

      params[:tags].each do |tag_value| 
        tag = Tag.find_or_create_by(name: tag_value, user_id: current_user.id)
        @meal.tags << tag 
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def controller?(*controller)
    controller.include?(params[:controller])
  end

  def action?(*action)
    action.include?(params[:action])
  end
  
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper

  def calculate_nutrition(list, type)
    sum = 0
    list.each do |x| 
      if x.meal && x.meal.nutrition && x.meal.nutrition.send(type)
        sum += x.meal.nutrition.send(type)
      elsif x.nutrition && x.nutrition.send(type)
        sum += x.nutrition.send(type)
      end
    end
    sum
  end


end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/directions/_direction.html.erb
<li>
  <div class="direction-counter"><%= direction_counter + 1 %></div>
  <div class="direction-text"><%= direction.step %></div>
</li>

app/views/entries/_meal.html.erb
<li>
  <div class="list-item">
    <%= entry.meal ? entry.meal.name : entry.note %>
  </div>
  
  <div class="toggleable">
      <ul class="nutrition">
        <% nutrition = entry.meal ? entry.meal.nutrition : entry.nutrition %>
        <% if nutrition %>
          <% if nutrition.calories %>
            <li>Calories: <%= nutrition.calories %></li>
          <% end %>
          <% if nutrition.protein %>
            <li>Protein: <%= nutrition.protein %> g</li>
          <% end %>
          <% if nutrition.carbs %>
            <li>Carbs: <%= nutrition.carbs %> g</li>
          <% end %>
          <% if nutrition.fat %>
            <li>Fat: <%= nutrition.fat %> g</li>
          <% end %>
        <% end %>
        <li>
          <%= link_to raw("<i class='fa fa-cutlery'></i>"), meal_path(entry.meal) unless entry.meal.nil? %>
          <%= link_to raw("<i class='fa fa-trash'></i>"), entry_path(entry), method: "delete" %>
        </li>
      </ul>
  </div>   
</li>

app/views/entries/_new_entry.html.erb
<%= form_for @entry do |f| %>

  <!-- BUTTONS -->
  <div class="row entries-modal">
    <div class="col-sm-12">
      <button class="btn btn-default select" type="button">Select A Meal</button>
      <div class="or">OR</div>
      <button class="btn btn-default quick-add" type="button">Quick Add</button>
    </div>
  </div>

  <!-- INPUTS -->
  <div class="row">
    <div class="col-sm-10 col-sm-offset-1">

      <!-- .SELECT-CHOSEN -->
      <div class="form-group select-chosen">
        <%= f.collection_select :meal_id, @user.meals, :id, :name, {prompt: "Select a meal"}, {class: "form-control"}  %>
      </div>

      <!-- .QUICK-ADD-CHOSEN -->
      <div class="form-group quick-add-chosen">
        <%= f.label :note, "Name" %><br>
        <%= f.text_field :note, class: "form-control" %>
      </div>

      <!-- BOTH -->
       <div class="form-group select-chosen quick-add-chosen">
        <%= f.label :tag, "Meal" %><br>
          <% if @meal_type %>
            <% @meal_type.each do |type| %>
              <%= f.radio_button(:meal_type, type) %> &nbsp;
              <%= f.label(:meal_type, type, class: "radio-button", value: type) %><br>
            <% end %>
          <% end %>
      </div>

       <!-- .QUICK-ADD-CHOSEN -->
       <div class="quick-add-chosen">
         <%= f.fields_for :nutrition do |ff| %>


          <!-- .QUICK-ADD-CHOSEN -->
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= ff.label :calories, "Nutrition" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <%= ff.number_field :calories, class: "form-control", placeholder: "Calories" %>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= ff.number_field :protein, class: "form-control", placeholder: "Protein (grams)" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                <%= ff.number_field :carbs, class: "form-control", placeholder: "Carbs (grams)" %>
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                <%= ff.number_field :fat, class: "form-control", placeholder: "Fat (grams)" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <!-- BOTH -->
      <%= f.hidden_field :day, value: params[:day] %>
      <%= f.hidden_field :user_id, value: @user.id %>

      <!-- SUBMIT BUTTON -->
      <div class="form-group button-wrapper select-chosen quick-add-chosen">
        <%= f.submit "Submit", class: "btn btn-default" %>
      </div>
    </div>
  </div>

<% end %>

app/views/entries/_nutrition.html.erb
<% sum = 0 %>
​
<% snack.each do |snack| %>
  <% nutrition = snack.meal ? snack.meal.nutrition : snack.nutrition %>
  <% sum += nutrition.calories %>
<% end %>
​
<%= sum %>

app/views/entries/index.html.erb
<% @is_fluid = true %>

  <div class="row">
    <div class="col-sm-12">
      <h1><%= @start.strftime("%a %-d") %> - <%= (@start+5.days).strftime("%a %-d") %></h1>
    </div>
  </div>

 <!-- NAV -->
  <nav>
    <ul class="pager">
      <li class="previous"><%= link_to raw("<span aria-hidden='true'>&larr;</span> Prev"), entries_path(:date => "#{@start-1.week}") %></li>
      <li><%= link_to "Today", entries_path %></li>
      <li class="next"><%= link_to raw("Next <span aria-hidden='true'>&rarr;</span>"), entries_path(:date => "#{@start+1.week}") %></li>
    </ul>
  </nav>

<!-- WEEK -->
<div class="row">
  <div class="week-wrapper">

    <!-- DAY  -->
    <% @week.each do |day| %>
        
      <div class="col-sm-2 day-wrapper">
        <h4><%= day.strftime("%a %-d") %></h4>
        <%= link_to raw("<i class='fa fa-plus'></i>"), "#entriesModal", :data => {:toggle => "modal", :day => day.strftime('%F')}, class: "modal-link pull-right" %>
        <br>

          <!-- BREAKFAST -->
          <% breakfast = Entry.where(meal_type: "Breakfast", day: day.strftime('%F'), user_id: @user.id) %>
            <% unless breakfast.empty? %>
              <h5>Breakfast</h5>
              <ul class="breakfast-list">
                <%= render partial: "meal", collection: breakfast, as: :entry %>
              </ul>
            <% end %>
        
          <!-- LUNCH -->
          <% lunch = Entry.where(meal_type: "Lunch", day: day.strftime('%F'), user_id: @user.id) %>
            <% unless lunch.empty? %>
              <h5>Lunch</h5>
              <ul class="lunch-list">
                <%= render partial: "meal", collection: lunch, as: :entry %>
              </ul>
            <% end %>
        
          <!-- DINNER -->
          <% dinner = Entry.where(meal_type: "Dinner", day: day.strftime('%F'), user_id: @user.id) %> 
            <% unless dinner.empty? %>
              <h5>Dinner</h5>
              <ul class="dinner-list">
                <%= render partial: "meal", collection: dinner, as: :entry %>
              </ul>
            <% end %>
        
          <!-- SNACK -->
          <% snack = Entry.where(meal_type: "Snack", day: day.strftime('%F'), user_id: @user.id) %>
            <% unless snack.empty? %>
              <h5>Snack</h5>
              <ul class="snack-list">
                <%= render partial: "meal", collection: snack, as: :entry %>
              </ul>
            <% end %>

          <% if breakfast.length > 0 || lunch.length > 0 || dinner.length > 0 || snack.length > 0 %>
          <% entriesForToday = Entry.where(day: day.strftime('%F')) %>
            <div class="day-nutrition">
              <h5>Total:</h5>
              <ul>
                <% 
                   calories = :calories 
                   protein  = :protein 
                   carbs    = :carbs 
                   fat      = :fat 
                %>
                <li>Calories: <span><%= calculate_nutrition(entriesForToday, calories) %></span></li>
                <li>Protein: <span><%= calculate_nutrition(entriesForToday, protein) %></span></li>
                <li>Carbs: <span><%= calculate_nutrition(entriesForToday, carbs) %></span></li>
                <li>Fat: <span><%= calculate_nutrition(entriesForToday, fat) %></span></li>
              </ul>
            </div>
          <% end %>
      </div> <!-- end of .day-wrapper -->

    <% end %>
  </div> <!-- end of .week-wrapper -->
 </div>



  <!-- MODAL -->
  <div class="modal fade" id="entriesModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">New Entry</h4>
        </div>

        <div class="modal-body">
          <%= render "new_entry" %>
        </div>
      
      </div>

app/views/ingredients/_ingredient.html.erb
<li class="ingredient-li">
  <i class="fa fa-caret-right"></i> <%= ingredient.amount %> <%= ingredient.name %>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Recipe App</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.2/js/select2.min.js"></script>
    <!-- GOOGLE FONTS -->
    <link href='https://fonts.googleapis.com/css?family=Quicksand:300|Open+Sans:400,300|Lobster' rel='stylesheet' type='text/css'>
    <!-- FONT AWESOME -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
  </head>

  <body>

    <!-- NAVBAR -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- LOGO -->
        <div class="navbar-header">
          <%= link_to root_path, class: "navbar-brand" do %>
            <%= image_tag("logo.png", class: "logo") %>
          <% end %>
        </div>
        <!-- LINKS -->
        <ul class="nav navbar-nav">
          <li><%= link_to "Entries", entries_path, class: "#{'active' if controller?('entries') && action?('index')}" %></li>
          <li><%= link_to "Meals", root_path, class: "#{'active' if controller?('meals') && action?('index')}" %></li>
          <li><%= link_to "New", new_meal_path, class: "#{'active' if controller?('meals') && action?('new')}" %></li>
      </ul>
      <ul class="logout nav navbar-nav navbar-right">
        <li><%= link_to "Logout", destroy_user_session_path, method: "delete", data: {confirm: "Are you sure?"}, class: "navbar-link" %></li>
      </ul>
      </div>
    </nav>

    <!-- CONTENT -->

    <div class="<%= @is_fluid ? "container-fluid" : "container" %>">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      
      <%= yield %>
      
    </div>

  </body>
</html>

app/views/meals/edit.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>Edit Meal</h1>
  </div>
</div>

<%= render 'form' %>

app/views/meals/index.html.erb
<div class="row">
  <div class="col-sm-12">
    <h1>Meals</h1>
  </div>
</div>

<!-- SEARCH -->
<div class="row">
  <div class="col-sm-7 col-sm-offset-2">
    <%= form_tag meals_path, :method => "get", class: "" do %>
      <div class="form-group">
        <%= text_field_tag :search, params[:search], placeholder: "Name, tag, type", class: "form-control input-lg" %>
      </div>
    </div>
    <div class="col-sm-2">
      <%= submit_tag "Search", :name => nil, class: "btn btn-default btn-lg" %>
    </div>
    <% end %>
  </div>

  
<!-- MEAL -->
<div class="index-wrapper row">
  
    <div class="col-sm-3 col-xs-12 pull-right">
      <ul class="tag-list list-unstyled">
        <% current_user.tags.each do |tag| %>
          <li><%= link_to tag.name, meals_path(tag: tag.name), class: "badge" %></li>
        <% end %>
      </ul>
    </div>
 
 <div class="col-sm-9">
  <% @meals.each do |meal| %>
    <div class="row meal-wrapper">
      <div class="meal-picture-wrapper col-sm-3 col-xs-12">
        <%= image_tag(meal.avatar.url, class: "meal-picture-index-page") if meal.avatar? %>
      </div>
      <div class="col-sm-8 col-xs-12">
        <h3 class="meal-name"><%= link_to meal.name, meal_path(meal) %></h3>
        <p><%= meal.description %></p>
        <% meal.tags.each do |tag| %>
          <%= link_to tag.name, meals_path(tag: tag.name), class: "badge" %>
        <% end %>
      </div>
    </div>

    <% end %>
  </div>
</div>

<!-- PAGINATION -->
<div class="row">
  <div class="pagination-wrapper">
    <div class="col-sm-12">
      <div class="pagination">
        <%= will_paginate @meals, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/meals/new.html.erb
<div class="row">
  <div class="col-xs-12">
    <h1>New Meal</h1>
  </div>
</div>

<%= render 'form' %>

app/views/meals/show.html.erb
<!-- JUMBOTRON -->
<div class="jumbotron" style="background-image: url(<%= @meal.avatar.url %>">
  <h1><%= @meal.name %></h1>
    <div class="show-page-buttons jumbotron-buttons">
        <%= link_to edit_meal_path(@meal), class: "btn btn-default" do %>
          <i class='fa fa-pencil'></i> 
        <% end %>
        <%= link_to meal_path, method: "delete", data: {confirm: "Are you sure?"}, class: "btn btn-default" do %>
          <i class='fa fa-trash'></i>
        <% end %>
    </div>
</div>

<!-- TAG/SERVINGS/DESCRIPTION -->
<div id="description-wrapper">
  <div class="row description">
    <div class="col-sm-8 col-sm-offset-2">
      <p class="description-paragraph"><%= @meal.description %></p>
    </div>
  </div>

  <div class="row description">
    <div class="col-sm-12">

      <!-- WHERE NUTRITION BLOCKS WILL GO -->

      <div class="description-buttons">
        <i class="fa fa-pie-chart"></i><br>
        <%= @meal.servings %> servings 
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-12 text-center">
      <% @meal.tags.each do |tag| %>
        <p class="badge"><%= tag.name %></p>
      <% end %>
    </div>
  </div>

  </div>



<div class="row">

  <!-- INGREDIENTS -->
  <div class="col-sm-4 col-sm-offset-2 col-xs-12 show-page-buttons">
    <h4 class="ingredients-header">Ingredients</h4>
    <% nutrition = @meal.nutrition %>
    <% if nutrition %>
      <%= link_to  "#nutritionModal", data: {toggle: "modal"}, class: "btn btn-default ingredients-modal-button" do %>
        <i class='fa fa-bar-chart'></i>
      <% end %>
    <% end %>
    <ul id="ingredients">
      <%= render partial: "ingredients/ingredient", collection: @ingredients %>
    </ul>
  </div>
  
  <!-- DIRECTIONS -->
  <div class="col-sm-4 col-xs-10 col-xs-offset-1">
    <h4 class="directions-header">Directions</h4>
    <ol id="directions">
      <%= render partial: "directions/direction", collection: @directions %>
    </ol>
  </div>

</div>


</div>

<!-- MODAL -->
  <div class="modal fade" id="nutritionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="myModalLabel">Nutritional Facts</h4>
        </div>

        <div class="modal-body">
            <ul class="nutrition-button-list">
              <% if nutrition %>
              <% if nutrition.calories %>
                <li>
                  <i class="fa fa-caret-right"></i>
                  <span>Calories:</span> <%= @meal.nutrition.calories %>
                </li>
              <% end %>
              <% if nutrition.protein %>
                <li>
                  <i class="fa fa-caret-right"></i>
                  <span>Protein:</span> <%= @meal.nutrition.protein %> g
                </li>
              <% end %>
              <% if nutrition.carbs %>
                <li>
                  <i class="fa fa-caret-right"></i>
                  <span>Carbs:</span> <%= @meal.nutrition.carbs %> g
                </li>
              <% end %>
              <% if nutrition.fat %>
                <li>
                  <i class="fa fa-caret-right"></i>
                  <span>Fat:</span> <%= @meal.nutrition.fat %> g
                </li>
              <% end %>
              <% end %>
            </ul>
        </div>
      </div>
      
    </div>
  </div>